- name:  Expense project setup
  hosts:  {{ role_name }}-dev-yml.chaitus.shop ansible_python_interpreter=/usr/bin/python3
    #"{{ role_name }}"
  # frontend-dev-yml.chaitus.shop
  become:  yes
  roles:
    - "{{ role_name }}"