- name:  Expense project setup
  hosts:  localhost
#  "{{ role_name }}-{{ env }}.chaitus.shop"
#  "{{ role_name }}-{{ env }}-yml.chaitus.shop" ----give this for ANSIBLE ..
#    "{{ role_name }}-{{ env }}-yml.chaitus.shop"
  # "{ role_name }}-{{ env }}.chaitus.shop" ..give this for terraform
#  localhost ..for terraform pull
  vars:
      ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
    - "{{ role_name }}"



#  hosts:  "{{ role_name }}-dev-yml.chaitus.shop" ansible_python_interpreter=/usr/bin/python3
    #"{{ role_name }}"
  # frontend-dev-yml.chaitus.shop
