- name:  Get Secrets
  hosts: 35.153.134.238
  #localhost
#  connection: local  # This forces Ansible to run locally
#  vars:
#    ssh: "{{ lookup('hashi_vault', 'secret=common/data/ansiblessh token={{vault_token}} url=https://vault.chaitus.shop:8200 validate_certs=False') }}"
  tasks:
    - name:  Create common secrets SSH file
      ansible.builtin.lineinfile:
        path:  ~/secrets.json
#        line:  "{{ssh}}"
        line:  "{{ lookup('hashi_vault', 'secret=common1/data/common token={{vault_token}} url=https://vault.chaitus.shop:8200 validate_certs=False') }}"
        create: yes

    - name: Create app secret file
      ansible.builtin.lineinfile:
          path: ~/app.json
          #        line:  "{{ssh}}"
          line: "{{ lookup('hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.chaitus.shop:8200 validate_certs=False') }}"
          create: yes
  
  
  
#"Username: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.chaitus.shop:8200 validate_certs=False')}}" ..it gets the full secrets like username and password
#line:  "Username: {{ ssh | community.general.json_query('user') }}" ...json search query
#  "ansible_user: {{ ssh.user }}\n ansible_password: {{ ssh.pass }} "