- name:  Get Secrets
  hosts:  localhost
  vars:
    ssh: "{{ lookup('hashi_vault', 'secret=common/data/ansiblessh token={{vault_token}} url=https://vault.chaitus.shop:8200 validate_certs=False')}}"
  tasks:
    - name:  Create secret file
      ansible.builtin.lineinfile:
        path:  secrets.json
        line:  "{{ssh}}"
        create: yes
  
  
  
  
#"Username: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.chaitus.shop:8200 validate_certs=False')}}" ..it gets the full secrets like username and password
#line:  "Username: {{ ssh | community.general.json_query('user') }}" ...json search query
#  "ansible_user: {{ ssh.user }}\n ansible_password: {{ ssh.pass }} "