format_version: 10
pipelines:
  frontend:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-21f7d58:
        git: https://github.com/iteration2-chaitu/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      -  dev:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type:  manual
          jobs:
            ansible-playbook:
              timeout: 0
              environment_variables:
                ANSIBLE_INVENTORY:  /home/ec2-user/expense-ansible/pipelines/Hosts
              tasks:
                - exec:
                    arguments:
                        - arguments:
                            - -c
                            - |
                              ansible-playbook -i /path/to/your/inventory/file -e ansible_user=ec2-user -e ansible_password=DevOps321 expense.yml -e role_name=mysql -e env=dev|
#                       -  ansible.sh
#                       -  frontend
                    command:  bash  # bash ansible.sh frontend
                    run_if: passed
