format_version: 10
pipelines:
  frontend:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-21f7d58:
        git: https://github.com/iteration2-chaitu/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      -  dev:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type:  manual
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      -  frontend
                    command:  bash  # bash ansible.sh frontend
                    run_if: passed
