- name : Download the Node exporter
  ansible.builtin.unarchive:
    src:  https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner: bin

- name : Copy the prometheus service file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name : Copy the prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-{{ version }}.linux-amd64/prometheus.yml

- name : Start the prometheus service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes