- name:  cleanup the old content
  ansible.builtin.file:
    path:  "{{app_loc}}"
    state:  absent

- name: Create a group expense
  ansible.builtin.group:
    name: expense
    state: present  # Ensure the group exists

- name: Create a user expense
  ansible.builtin.user:
    name: expense              # Username
    groups: expense           # Add the user to the 'wheel' group (sudo group)
    state: present          # Ensure the user is present (created)

- name:  create the app directory
  ansible.builtin.file:
    path:  "{{app_loc}}"
    state:  directory
    owner: "{{app_user}}"
    group: "{{app_user}}"

- name:  Download and extract the app content
  ansible.builtin.unarchive:
    src:  https://expense-artifacts.s3.amazonaws.com/expense-{{component}}-v2.zip
    dest:  "{{app_loc}}"
    remote_src:  yes
    owner: "{{app_user}}"
    group: "{{app_user}}"